### ISSUE TITLE
Some animators don't export correctly

### ISSUE THREAD

**Issue by Roachdaripper** [Razmoth/GenshinStudio#19]
There are some animators that don't export correctly with or without animationclips, a good example being Lupas Boreas, exporting any of the animators exports an FBX with no textures which crashes noesis if loaded.

**Comment by Razmoth** [comment]
Greetings.

It depends on the animator being extracted.

In Lupas Boreas case there's `Echo` and `Normal` animators, the former being the shadows summoned sometimes during the fight and the latter is the actual model/animator used in-game.

**Comment by Roachdaripper** [comment]
> In Lupas Boreas case there's `Echo` and `Normal` animators, the former being the shadows summoned sometimes during the fight and the latter is the actual model/animator used in-game.

Yeah neither seem to work unfortunately :/
But great work on this version of GenshinStudio, I hope humanoid animation gets figured out someday!

**Comment by Razmoth** [comment]
Tried to export it myself and it works on `Noesis`

Another user confirmed that it's working as well.
![unknown](https://user-images.githubusercontent.com/32140579/183090061-88bebe1d-1d29-4b53-ab7b-b3a5eefec291.png)

Not sure where did it go exactly wrong on your side, might suggest to build from source if the issue is still present.

As for humanoid animations, unfortunately that won't be possible due to the fact that `Humanoid` relies heavily on `Unity` engine itself to run/work properly, so the only option is to use other tools such as ![AssetRipper](https://github.com/AssetRipper/AssetRipper) or ![uTinyRipper](https://github.com/mafaca/UtinyRipper).

**Comment by Roachdaripper** [comment]
> Tried to export it myself and it works on `Noesis`
I'll check again, thanks!

> As for humanoid animations, unfortunately that won't be possible due to the fact that `Humanoid` relies heavily on `Unity` engine itself to run/work properly, so the only option is to use other tools such as ![AssetRipper](https://github.com/AssetRipper/AssetRipper) or ![uTinyRipper](https://github.com/mafaca/UtinyRipper).
Is there a way to rip the animators and clips directly without converting them to FBX then perhaps? So that these other tools work without having to find someone who can make a fork to add BLK compatibility? Someone also suggested finding out what version of Unity GEIM runs on in-order to import the files directly into a build of unity in-order to convert them back to a standard animation format

**Comment by Razmoth** [comment]
As of now, Genshin Impact uses `ACL` to compress transform curves, which will not run natively on unity ripping tools since it's a new thing done by mihoyo.

There's a possibility of a tool (as you might've read in updated README) that should convert these customization into native unity again, you can read more about it and give your feedback when you have time, It'll be much appreciated.
