### ISSUE TITLE
Bug or incorrect usage?

### ISSUE THREAD

**Issue by Diamond-Frost** [Razmoth/GenshinStudio#8]
I downloaded the latest version (0.16.30) and started it, built the blk map, and loaded in the `GenshinImpact_Data` folder (same one as used for building the map) and then wanted to export all Models (Models -> Export all objects) which worked great, however, after around 5h, something on my PC happened and the process died (cause is known and isn't related to Genshin Studio) 

When I then started the program again, and selected the very same folder, it told me that pretty much all my blk files were not in the dictionary! It could from then on only load the level0/1/2/3/4/5, shared assets files (the ones right in the GenshinImpact_Data folder, not any subfolder)

I've tried the StreamingAssets folder exclusively, which somehow can load all the blk files contained within, despite the map being made from a folder above and on my initial run, it worked without explicitly selecting the StreamingAssets subfolder, it loaded everything from there

BTW, I recommend a Pause Export button!

**Comment by Diamond-Frost** [comment]
Since I didn't mention it, I've tried:

- Moving the GenshinImpact folder
- Deleting the BLKMap.bin file and rebuilding the map
- Rebuilding the map without deleting the bin file
- Downloading the version again, and replace my previous install+moving the install (deleted the original one, then extracted the new version into a differently named folder [GenshinStudio -> net5.0-windows])

**Comment by StoneMoe** [comment]
Try CAB method:
1. File - Extract folder - select GenshinImpact_Data folder - extract to your workspace folder
2. Build CABmap for your workspace folder
3. Option - Specify AI version - select correct game version
4. File - Load folder - select your workspace folder

**Comment by Razmoth** [comment]
Greetings,

Thanks for reporting the issue, sorry for the delayed response.

Could you provide the `BLKMap` file and the screenshot of logs when a `.blk` file is dragged and dropped into `GenshinStudio`, you can email it if you don't want to upload it here, then I'll have a look.

The new dependency format was designed with `BLKMap` in mind, I did some testing on `CABMap` but not enough to ensure that is ready for usage.

It'll need more Investigation, but with more time invested into researching dependencies, `CABMap` will eventually be discontinued due to `BLKMap` ability to achieve what `CABMap` does, with "almost" similar preformance.

**Comment by Razmoth** [comment]
Greetings,

Can you try the latest [release](https://github.com/Razmoth/GenshinStudio/releases/tag/v0.16.40) and see if this issue is still present or not ?

Thank you for your understanding.
